package:
  name: apko
  version: "0.25.4"
  epoch: 0
  description: Build OCI images using APK directly without Dockerfile
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/apko
      tag: v${{package.version}}
      expected-commit: 352a64da25397ab97b18c107f1e3c3df2a709c62

  - uses: go/build
    with:
      output: apko
      packages: .
      ldflags: |
        -buildid= \
        -X $(PKG).gitVersion=$(git describe --dirty --tags --always) \
        -X $(PKG).gitCommit=$(git rev-parse HEAD) \
        -X $(PKG).gitTreeState=$(shell git diff --quiet >/dev/null 2>&1 || echo "dirty" || echo "clean") \
        -X $(PKG).buildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

test:
  pipeline:
    - runs: |
        apko version || exit 1
        apko --help
    - runs: |
        cat <<EOF >> /tmp/wolfi-base.yaml
        contents:
          keyring:
            - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
          repositories:
            - https://packages.wolfi.dev/os
          packages:
            - wolfi-base

        cmd: /bin/sh -l

        archs:
        - x86_64
        - aarch64
        EOF

        apko build  /tmp/wolfi-base.yaml test test.tar

update:
  enabled: true
  github:
    identifier: chainguard-dev/apko
    strip-prefix: v
    use-tag: true
